function varargout = findIpeaks(x,y,varargin)
	[varargout{1:nargout}] = findpeaks(y,x,...
								'MinPeakHeight',max(y./2),...'SortStr','descend','NPeaks',10,...
								'MinPeakProminence',max(y./2),...
								'Annotate','extents');
end
